name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]
    paths:
      - '**/*.py'
      - 'requirements.txt'
      - '.github/workflows/ci.yml'

jobs:
  lint-test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Syntax check
        run: |
          python -m py_compile $(git ls-files '*.py' | tr '\n' ' ')

      - name: Import smoke
        run: |
          python - << 'PY'
          from importlib import import_module
          import_module('main')
          print('Import OK')
          PY

